version: '3.8'
services:
  backforfrontend:
    # Usar la imagen publicada en Docker Hub en lugar de construir localmente
    image: benjamorenoo/bff-sanos-salvos:latest
    container_name: backforfrontend
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - PORT=3000
      - USERS_URL=http://ms-users:3002/api
      - REPORTS_URL=http://ms-mascotas:3003
    networks:
      - sanos-y-salvos-net

networks:
  sanos-y-salvos-net:
    external: true
    name: ms_mascotas_sanos-y-salvos-net
