version: '3.8'
services:
  backforfrontend:
    build: .
    container_name: backforfrontend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - AUTH_URL=http://ms-auth:3001/api
      - USERS_URL=http://ms-users:3002/api
      - REPORTS_URL=http://ms-mascotas:3003
      - MASCOTAS_URL=http://ms-mascotas:3003
      - LOCALIZACION_URL=http://ms-localizacion:3004
      - SOPORTE_URL=http://ms-soporte:3005/api
      - MATCHING_URL=http://ms-matching:3005
    networks:
      - sanos-y-salvos-net

networks:
  sanos-y-salvos-net:
    external: true
    name: mascotas_sanos-y-salvos-net
